# Numpy

In [3]:
import numpy as np

In [7]:
a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [10]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a3 = np.array([[[1, 2, 3], [3, 4, 5]], [[9, 10, 11], [12, 13, 14]], [[15, 16, 17], [18, 10, 20]]])
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 10, 20]]])

In [18]:
a1[1]

2

In [21]:
a2[1, 2]

6

In [26]:
a3[1, 0, 1]

10

In [32]:
av = np.empty([4,3])
av

array([[4.63651994e-310, 0.00000000e+000, 1.01855798e-312],
       [9.54898106e-313, 1.10343781e-312, 1.03977794e-312],
       [1.23075756e-312, 1.12465777e-312, 1.03977794e-312],
       [9.76118064e-313, 1.01855798e-312, 1.90979621e-312]])

In [35]:
az = np.zeros([3,5])
az

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
ao = np.ones([3,5])
ao

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
af = np.full([3,5], 9)
af

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [45]:
ai = np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [50]:
ar = np.arange(1, 10, 2)
ar

array([1, 3, 5, 7, 9])

In [52]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
          axis=0)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples

In [54]:
al = np.linspace(1, 100, 20)
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [57]:
aran = np.random.random([2,3])
aran

array([[0.73892315, 0.71663982, 0.8497389 ],
       [0.20731596, 0.90810802, 0.78902793]])

In [59]:
aran.ndim

2

In [61]:
aran.shape

(2, 3)

In [63]:
aran.size

6

In [65]:
aran.dtype

dtype('float64')

In [71]:
at = np.array(['hola','mundo'])
at.dtype

dtype('<U5')

In [75]:
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [77]:
np.info(al.astype)

a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

Parameters
----------
dtype : str or dtype
    Typecode or data-type to which the array is cast.
order : {'C', 'F', 'A', 'K'}, optional
    Controls the memory layout order of the result.
    'C' means C order, 'F' means Fortran order, 'A'
    means 'F' order if all the arrays are Fortran contiguous,
    'C' order otherwise, and 'K' means as close to the
    order the array elements appear in memory as possible.
    Default is 'K'.
casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'unsafe'
    for backwards compatibility.

      * 'no' means the data types should not be cast at all.
      * 'equiv' means only byte-order changes are allowed.
      * 'safe' means only casts which can preserve values are allowed.
      * 'same_kind' means only safe casts or casts within a kind,
        like float64

In [79]:
al.astype('i')

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100], dtype=int32)

In [86]:
aran

array([[0.73892315, 0.71663982, 0.8497389 ],
       [0.20731596, 0.90810802, 0.78902793]])

In [93]:
np.sort(aran, axis=0)

array([[0.20731596, 0.71663982, 0.78902793],
       [0.73892315, 0.90810802, 0.8497389 ]])

In [94]:
arr = np.array([2, 4, 5, 0, 6, 1, 5, 4, 1, -3])

In [96]:
np.min(arr)

-3

In [98]:
np.max(arr)

6

In [100]:
np.mean(arr)

2.5

In [102]:
np.median(arr)

3.0

In [104]:
np.std(arr)

2.6551836094703507

In [106]:
np.absolute(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [108]:
np.abs(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [110]:
np.cumsum(arr)

array([ 2,  6, 11, 11, 17, 18, 23, 27, 28, 25])

In [112]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [117]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 1.00000000e+00,
       4.03428793e+02, 2.71828183e+00, 1.48413159e+02, 5.45981500e+01,
       2.71828183e+00, 4.97870684e-02])

In [119]:
np.prod(arr)

0

In [125]:
np.NaN

nan

In [128]:
for x in arr:
    print(x)

2
4
5
0
6
1
5
4
1
-3


In [130]:
for i in range(len(arr)):
    print(i, arr[i])

0 2
1 4
2 5
3 0
4 6
5 1
6 5
7 4
8 1
9 -3


In [133]:
for x in aran:
    for y in x:
        print(y)

0.7389231469169285
0.7166398240275199
0.8497389007144622
0.2073159599963018
0.9081080178594217
0.789027930029842


In [135]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 10, 20]]])

In [137]:
for x in a3:
    for y in x:
        for z in y:
            print(z)

1
2
3
3
4
5
9
10
11
12
13
14
15
16
17
18
10
20


In [139]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read


In [141]:
for x in np.nditer(a3):
    print(x)

1
2
3
3
4
5
9
10
11
12
13
14
15
16
17
18
10
20


In [143]:
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [145]:
for pos, x in np.ndenumerate(a3):
    print(pos, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(1, 0, 0) 9
(1, 0, 1) 10
(1, 0, 2) 11
(1, 1, 0) 12
(1, 1, 1) 13
(1, 1, 2) 14
(2, 0, 0) 15
(2, 0, 1) 16
(2, 0, 2) 17
(2, 1, 0) 18
(2, 1, 1) 10
(2, 1, 2) 20


In [147]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [154]:
np.where(a3 > 5)

(array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [156]:
a1

array([1, 2, 3])

In [166]:
a2[(a2 > 1) & (a2 % 2 == 0)]

array([2, 4, 6])

In [163]:
a1[:2]

array([1, 2])

In [167]:
a2[:2,1:]

array([[2, 3],
       [5, 6]])

In [179]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.concatenate((arr1, arr2), axis=1)
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [185]:
arrs = np.stack((arr1, arr2), axis=0)
arrs

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [188]:
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [197]:
splitted = np.array_split(arr, 3,axis=0)
splitted

for s in splitted:
    print(s)

[[1 2 3 7 8 9]]
[[ 4  5  6 10 11 12]]
[]


In [215]:
arr = np.array([1, 2, np.nan, 7, 4, 0])
print(arr)
sum(arr)

[ 1.  2. nan  7.  4.  0.]


nan

In [212]:

for pos in range(len(arr)):
    if np.isnan(arr[pos]):
        arr[pos] = 0

print(arr)

[1. 2. 0. 7. 4. 0.]


In [220]:
lista = [x for x in arr if not np.isnan(x)]
np.array(lista)

array([1., 2., 7., 4., 0.])

In [221]:
np.isnan(arr)

array([False, False,  True, False, False, False])

In [223]:
arr[np.logical_not(np.isnan(arr))]

array([1., 2., 7., 4., 0.])

In [225]:
arr[np.isfinite(arr)]

array([1., 2., 7., 4., 0.])

In [229]:
copia = arr.copy()
vista = arr.view()

print('original:', arr)
print('copia:', copia)
print('vista:', vista)

arr[0] = 67

print('original:', arr)
print('copia:', copia)
print('vista:', vista)


original: [67.  2. nan  7.  4.  0.]
copia: [67.  2. nan  7.  4.  0.]
vista: [67.  2. nan  7.  4.  0.]
original: [67.  2. nan  7.  4.  0.]
copia: [67.  2. nan  7.  4.  0.]
vista: [67.  2. nan  7.  4.  0.]


In [231]:
arr.dtype

dtype('float64')

In [236]:
vista = arr.view(dtype=np.int32)
print('vista:', vista)

np.info(arr.view)

vista: [         0 1079033856          0 1073741824          0 2146959360
          0 1075576832          0 1074790400          0          0]
a.view([dtype][, type])

New view of array with the same data.

.. note::
    Passing None for ``dtype`` is different from omitting the parameter,
    since the former invokes ``dtype(None)`` which is an alias for
    ``dtype('float_')``.

Parameters
----------
dtype : data-type or ndarray sub-class, optional
    Data-type descriptor of the returned view, e.g., float32 or int16.
    Omitting it results in the view having the same data-type as `a`.
    This argument can also be specified as an ndarray sub-class, which
    then specifies the type of the returned object (this is equivalent to
    setting the ``type`` parameter).
type : Python type, optional
    Type of the returned view, e.g., ndarray or matrix.  Again, omission
    of the parameter results in type preservation.

Notes
-----
``a.view()`` is used two different ways:

``a.view(some_dt